INSERT INTO Person (email, password, role, name, surname, age, gender) VALUES ('paris@gokdis.ecosys.eu', '$2a$10$09hMiVpHihzoG9RLxRY7BO7JtzevbrEXOjXW4K2DFzWw1R61pJLq6', 'ROLE_USER', 'Paris', 'of Troy', 13, 'Male');
INSERT INTO Person (email, password, role, name, surname, age, gender) VALUES ('kerberos@gokdis.ecosys.eu', '$2a$10$MJDvLK2KE0EMkoBGKDeq7es68iLOGOvbZg3M1WQ646z18zK3J3Zzm', 'ROLE_MOD', 'Kerberos', 'of Tartarus', 14, 'Other');
INSERT INTO Person (email, password, role, name, surname, age, gender) VALUES ('helen@gokdis.ecosys.eu', '$2y$10$2ufVtBR5Ha6KuqB/6lXtDewp/HQv/hIkruUd7ecWGYnXJFalYJ2cS', 'ROLE_ADMIN', 'Helen', 'of Troy', 15, 'Female');

INSERT INTO Beacon (mac, id, x, y) VALUES ('f5:e5:8c:26:db:7a', '10000', 0, 0);
INSERT INTO Beacon (mac, id, x, y) VALUES ('eb:6f:20:3b:89:e2', '10002', 1, 0);
INSERT INTO Beacon (mac, id, x, y) VALUES ('c7:10:69:07:fb:51', '26268', 1, 1);